CREATE NODE TABLE IF NOT EXISTS Entity(id STRING, label STRING, properties STRING, PRIMARY KEY(id));
CREATE NODE TABLE IF NOT EXISTS Agent(id STRING, personaJson STRING, simulationId STRING, PRIMARY KEY(id));
CREATE REL TABLE IF NOT EXISTS KNOWS(FROM Agent TO Agent, weight FLOAT, context STRING);
CREATE REL TABLE IF NOT EXISTS MENTIONED_IN(FROM Entity TO Entity, source STRING);
CREATE REL TABLE IF NOT EXISTS HAS_TRAIT(FROM Agent TO Entity, strength FLOAT);
CREATE NODE TABLE IF NOT EXISTS _Migrations(name STRING, appliedAt STRING, PRIMARY KEY(name));
